CREATE TABLE IF NOT EXISTS checks (
    check_id INT AUTO_INCREMENT PRIMARY KEY,
    check_name VARCHAR(255),
    check_type VARCHAR(255),
    check_category VARCHAR(255),
    category_sort_id INT,
    check_sort_id INT,
    check_status INT,
    check_price INT,
    check_block INT,
    check_configuration JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
ALTER TABLE checks ADD CONSTRAINT temp_unique_check UNIQUE (check_name);

INSERT IGNORE INTO checks (check_name, check_type, check_category, category_sort_id, check_sort_id, check_status, check_price, check_block, check_configuration) VALUES
('Aadhaar card', 'API', 'Nationality', 1, 1, 1, 3, 10, '{"isRecurring": true, "fieldsExpected": null, "isCheckDropdown": true, "recurringOptions": {"options": ["Monthly", "Quarterly", "Biannually", "Annually"], "selectType": "single"}, "expectedDocuments": null, "isExpectingFields": false, "isExpectingDocument": false, "checkDropDownOptions": null}'),
('Driving license', 'API', 'Nationality', 1, 5, 1, 3, 10, '{"isRecurring": true, "fieldsExpected": null, "isCheckDropdown": false, "recurringOptions": {"options": ["Monthly", "Quarterly", "Biannually", "Annually"], "selectType": "single"}, "expectedDocuments": null, "isExpectingFields": false, "isExpectingDocument": false, "checkDropDownOptions": null}'),
('PAN card', 'API', 'Nationality', 1, 2, 1, 3, 10, '{"isRecurring": true, "fieldsExpected": null, "isCheckDropdown": false, "recurringOptions": {"options": ["Monthly", "Quarterly", "Biannually", "Annually"], "selectType": "single"}, "expectedDocuments": null, "isExpectingFields": false, "isExpectingDocument": false, "checkDropDownOptions": null}'),
('Voter ID', 'API', 'Nationality', 1, 4, 1, 3, 10, '{"isRecurring": true, "fieldsExpected": null, "isCheckDropdown": false, "recurringOptions": {"options": ["Monthly", "Quarterly", "Biannually", "Annually"], "selectType": "single"}, "expectedDocuments": null, "isExpectingFields": false, "isExpectingDocument": false, "checkDropDownOptions": null}'),
('Passport', 'API', 'Nationality', 1, 3, 1, 3, 10, '{"isRecurring": true, "fieldsExpected": null, "isCheckDropdown": false, "recurringOptions": {"options": ["Monthly", "Quarterly", "Biannually", "Annually"], "selectType": "single"}, "expectedDocuments": null, "isExpectingFields": false, "isExpectingDocument": false, "checkDropDownOptions": null}'),
('Highest qualification', 'PARTNER', 'Education', 2, 1, 1, 3, 10, '{"isRecurring": false, "fieldsExpected": null, "isCheckDropdown": false, "recurringOptions": null, "expectedDocuments": {"options": ["Marksheet", "Certificate", "Both"], "selectType": "single"}, "isExpectingFields": false, "isExpectingDocument": true, "checkDropDownOptions": null}'),
('10th board', 'PARTNER', 'Education', 2, 8, 1, 3, 10, '{"isRecurring": false, "fieldsExpected": null, "isCheckDropdown": false, "recurringOptions": null, "expectedDocuments": {"options": ["Marksheet", "Certificate", "Both"], "selectType": "single"}, "isExpectingFields": false, "isExpectingDocument": true, "checkDropDownOptions": null}'),
('12th board', 'PARTNER', 'Education', 2, 7, 1, 3, 10, '{"isRecurring": false, "fieldsExpected": null, "isCheckDropdown": false, "recurringOptions": null, "expectedDocuments": {"options": ["Marksheet", "Certificate", "Both"], "selectType": "single"}, "isExpectingFields": false, "isExpectingDocument": true, "checkDropDownOptions": null}'),
('Degree', 'PARTNER', 'Education', 2, 5, 1, 3, 10, '{"isRecurring": false, "fieldsExpected": null, "isCheckDropdown": false, "recurringOptions": null, "expectedDocuments": {"options": ["Marksheet", "Certificate", "Both"], "selectType": "single"}, "isExpectingFields": false, "isExpectingDocument": true, "checkDropDownOptions": null}'),
('Post graduation', 'PARTNER', 'Education', 2, 4, 1, 3, 10, '{"isRecurring": false, "fieldsExpected": null, "isCheckDropdown": false, "recurringOptions": null, "expectedDocuments": {"options": ["Marksheet", "Certificate", "Both"], "selectType": "single"}, "isExpectingFields": false, "isExpectingDocument": true, "checkDropDownOptions": null}'),
('Master of philosophy', 'PARTNER', 'Education', 2, 3, 1, 3, 10, '{"isRecurring": false, "fieldsExpected": null, "isCheckDropdown": false, "recurringOptions": null, "expectedDocuments": {"options": ["Marksheet", "Certificate", "Both"], "selectType": "single"}, "isExpectingFields": false, "isExpectingDocument": true, "checkDropDownOptions": null}'),
('Doctor of philosophy', 'PARTNER', 'Education', 2, 2, 1, 3, 10, '{"isRecurring": false, "fieldsExpected": null, "isCheckDropdown": false, "recurringOptions": null, "expectedDocuments": {"options": ["Marksheet", "Certificate", "Both"], "selectType": "single"}, "isExpectingFields": false, "isExpectingDocument": true, "checkDropDownOptions": null}'),
('Criminal history', 'PARTNER', 'Criminal background', 4, 1, 1, 5, 10, '{"isRecurring": true, "fieldsExpected": null, "isCheckDropdown": false, "recurringOptions": {"options": ["Monthly", "Quarterly", "Biannually", "Annually"], "selectType": "single"}, "expectedDocuments": null, "isExpectingFields": false, "isExpectingDocument": false, "checkDropDownOptions": null}'),
('Employment based on', 'PARTNER', 'Work experience', 3, 1, 1, 8, 10, '{"isRecurring": false, "fieldsExpected": null, "isCheckDropdown": true, "recurringOptions": null, "expectedDocuments": {"options": ["Appointment Letter", "Release Letter", "Certificates", "Letter"], "selectType": "multi"}, "isExpectingFields": false, "isExpectingDocument": true, "checkDropDownOptions": {"count": true, "options": ["No. of years", "No. of Employment", "All previous employments"], "countValue": 0, "selectType": "single"}}'),
('Diploma', 'PARTNER', 'Education', 2, 6, 1, 3, 10, '{"isRecurring": false, "fieldsExpected": null, "isCheckDropdown": false, "recurringOptions": null, "expectedDocuments": {"options": ["Marksheet", "Certificate", "Both"], "selectType": "single"}, "isExpectingFields": false, "isExpectingDocument": true, "checkDropDownOptions": null}'),
('Professional reference', 'PARTNER', 'References', 5, 1, 1, 100, 10, '{"isRecurring": false, "fieldsExpected": [{"key": "referenceName", "name": "Reference Name", "type": "textField", "sortId": 1, "hintText": "Reference Name", "maxInput": 255, "labelText": null, "isRequired": true, "keyboardType": "name", "validationType": "name"}, {"key": "referenceCompany", "name": "Company", "type": "textField", "sortId": 2, "hintText": "Company", "maxInput": 255, "labelText": null, "isRequired": true, "keyboardType": "name", "validationType": "name"}, {"key": "referenceDesignation", "name": "Designation", "type": "textField", "sortId": 3, "hintText": "Designation", "maxInput": 255, "labelText": null, "isRequired": true, "keyboardType": "name", "validationType": "name"}, {"key": "referenceContact", "name": "Phone", "type": "textField", "sortId": 4, "hintText": "Phone", "maxInput": 10, "labelText": null, "isRequired": true, "keyboardType": "number", "validationType": "mobile"}, {"key": "referenceEmail", "name": "Email", "type": "textField", "sortId": 5, "hintText": "Email", "maxInput": 255, "labelText": null, "isRequired": true, "keyboardType": "emailAddress", "validationType": "email"}, {"key": "isConsentTaken", "name": null, "type": "checkBox", "sortId": 6, "hintText": null, "maxInput": null, "labelText": "I have taken consent from the references to share their contact details", "isRequired": true, "keyboardType": null, "validationType": null}], "isCheckDropdown": true, "recurringOptions": null, "expectedDocuments": null, "isExpectingFields": true, "isExpectingDocument": false, "checkDropDownOptions": {"count": true, "options": null, "countValue": 1, "selectType": null}}');

ALTER TABLE checks DROP INDEX temp_unique_check;
