CREATE TABLE IF NOT EXISTS permissions (
    permission_id INT PRIMARY KEY,
    permission_name VARCHAR(255),
    permission_description TEXT,
    application VARCHAR(50),
    status TINYINT,
    created_by INT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
ALTER TABLE permissions ADD CONSTRAINT temp_unique_check UNIQUE (permission_id);

INSERT IGNORE INTO permissions (permission_id, permission_name, permission_description, application, status, created_by) VALUES
(1, 'VIEW_DASHBOARD_ENTERPRISE', 'Used to view dashboard of enterprise', 'Enterprise', 1, 0),
(2, 'VIEW_DASHBOARD_PARTNER', 'Used to view dashboard of partner', 'Partner', 1, 0),
(3, 'EDIT_DASHBOARD_ENTERPRISE', 'User can modify the widgets to be used in dashboard', 'Enterprise', 1, 0),
(4, 'EDIT_DASHBOARD_PARTNER', 'User can modify the widgets to be used in dashboard', 'Partner', 1, 0),
(5, 'INITIATE_SINGLE_CHECK_ENTERPRISE', 'Used for only single check', 'Enterprise', 1, 0),
(6, 'INITIATE_BULK_CHECK_ENTERPRISE', 'Used for both single and bulk initaite check', 'Enterprise', 1, 0),
(7, 'VIEW_CHECK_STATUS_REPORT', 'Used for view status report', 'Enterprise', 1, 0),
(8, 'VIEW_SUMMARY_REPORT', 'Used for only viewing summary report', 'Enterprise', 1, 0),
(9, 'DOWNLOAD_SUMMARY_REPORT', 'Used for view and download summary report', 'Enterprise', 1, 0),
(10, 'VIEW_DETAILED_REPORT', 'Used for only viewing detailed report', 'Enterprise', 1, 0),
(11, 'DOWNLOAD_DETAILED_REPORT', 'Used for view and download detailed report', 'Enterprise', 1, 0),
(12, 'CREATE_VISITING_CARD', 'Used for both create and view personal visiting card', 'Enterprise', 1, 0),
(13, 'INITIATE_CHECK_ENTERPRISE', 'Used for both download individual user documents and initiate check', 'Partner', 1, 0),
(14, 'VERIFY_CHECK', 'Used for Checker to check the status', 'Partner', 1, 0),
(15, 'VIEW_STATUS_REPORT', 'Used for status report', 'Partner', 1, 0),
(16, 'UPDATE_ENTERPRISE_INFORMATION', 'Used for view and updating enterprise basic information like address etc', 'Enterprise', 1, 0),
(17, 'VIEW_EMPLOYEE_DETAILS_ENTERPRISE', 'Used to view all employees under organization', 'Enterprise', 1, 0),
(18, 'ADD_EMPLOYEE_ENTERPRISE', 'Used to add employee under organization', 'Enterprise', 1, 0),
(19, 'ENABLE/DISABLE_EMPLOYEE_ENTERPRISE', NULL, 'Enterprise', 1, 0),
(20, 'VIEW_ENTERPRISE_DETAILS_ENTERPRISE', 'Used to only view enterprise details', 'Enterprise', 1, 0),
(21, 'ADD_EMPLOYEE_PARTNER', 'Add and View Partner Employee', 'Partner', 1, 0),
(23, 'VIEW_EMPLOYEE_DETAILS_PARTNER', 'View Partner Employee', 'Partner', 1, 0),
(24, 'ENABLE/DISABLE_EMPLOYEE_PARTNER', NULL, 'Partner', 1, 0),
(25, 'VIEW_CHECKS_ENTERPRISE', 'Used to view checks which can be used to create template', 'Enterprise', 1, 0),
(26, 'ADMIN_DASHBOARD', NULL, 'Enterprise', 1, 0),
(27, 'ADMIN_DASHBOARD', NULL, 'Partner', 1, 0),
(28, 'VIEW_ALL_TEMPLATES', NULL, 'Enterprise', 1, 0),
(29, 'EDIT_ALL_TEMPLATES', NULL, 'Enterprise', 1, 0),
(30, 'ADD_TEMPLATE', NULL, 'Enterprise', 1, 0),
(31, 'DELETE_ALL_TEMPLATES', NULL, 'Enterprise', 1, 0),
(32, 'AUTHORIZED_SIGNATORY', 'User who will have the right to give final sign on the reports', 'Partner', 1, 0),
(33, 'VIEW_PII_DATA', 'View masked data', 'Enterprise', 1, 0),
(34, 'VIEW_PII_DATA', 'View masked data', 'Partner', 1, 0),
(35, 'VIEW_NOTIFICATIONS', 'Used to view notifications of enterprise', 'Enterprise', 1, 0),
(36, 'VIEW_NOTIFICATIONS', 'Used to view notifications of partner', 'Partner', 1, 0),
(37, 'OPERATIONS_FILTER_LIST_VIEW', 'Used for saved filter list view.', 'Admin', 1, 0),
(38, 'OPERATIONS_FILTER_CREATE', 'Used for creating the saved filter and generating report from filter.', 'Admin', 1, 0),
(45, 'OPERATIONS_FILTER_VIEW', 'Used to view the filter selected by user.', 'Admin', 1, 0),
(46, 'OPERATIONS_FILTER_EDIT', 'Used to edit the filter saved.', 'Admin', 1, 0),
(47, 'OPERATIONS_FILTER_DELETE', 'Used for delete saved filter.', 'Admin', 1, 0),
(48, 'OPERATIONS_REPORT_GENERATE', 'Used for report generation.', 'Admin', 1, 0),
(49, 'OPERATIONS_REPORT_LIST_VIEW', 'Used for all report list view.', 'Admin', 1, 0),
(50, 'OPERATIONS_REPORT_DOWNLOAD', 'Used for downloading the report.', 'Admin', 1, 0),
(51, 'VIEW_CHECK_STATUS_REPORT_PARTNER', 'Used for view status report', 'Partner', 1, 0),
(54, 'DOWNLOAD_SUMMARY_REPORT_PARTNER', 'Used for view and download summary report', 'Partner', 1, 0),
(55, 'DOWNLOAD_DETAILED_REPORT_PARTNER', 'Used for view and download detailed report', 'Partner', 1, 0);

ALTER TABLE permissions DROP INDEX temp_unique_check;
